-- INSERT INTO roles (role) value ('STUDENT');
-- INSERT INTO roles (role) value ('ADMIN');
-- INSERT INTO roles (role) value ('REGISTRAR');
-- INSERT INTO roles (role) value ('HOD');
-- INSERT INTO roles (role) value ('DEAN');
